jsonnet: Add jsonnet files to generate manifests
observatorium/up pull request #27
Opened 2020-11-09 14:30 UTC by kakkoyun

Signed-off-by: Kemal Akkoyun <kakkoyun@gmail.com>

2020-11-09 14:49 UTC, bwplotka approved these changes
Nice, thanks! :muscle: 
LGTM

2020-11-10 10:01 UTC, metalmatze commented on jsonnet/main.jsonnet
> +local up = (import 'lib/up.libsonnet')(commonConfig);
```suggestion
local up = (import './lib/up.libsonnet')(commonConfig);
```

2020-11-10 10:02 UTC, metalmatze commented on jsonnet/main.jsonnet
> +local job = (import 'lib/job/up.libsonnet')(commonConfig { backoffLimit: 5 });
```suggestion
local job = (import './lib/job/up.libsonnet')(commonConfig { backoffLimit: 5 });
```

2020-11-10 10:03 UTC, metalmatze requested changes

2020-11-10 10:03 UTC, metalmatze commented on jsonnet/jsonnetfile.json
> +    }
Definitely remove this local dependency, but probably we don't need this file anymore to begin with.

2020-11-10 14:25 UTC, merged